/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PhishingEmailDetector;

public class App {
    public static void main(String[] args) {
        EmailParser emailParser;
        if (args.length > 0) {
            emailParser = new EmailParser(args[0]);
            emailParser.testEmails();
        } else {
            System.out.println("Usage: gradle run --args=\"<email file path>\"");
        }

    }
}
