/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PhishingEmailDetector;

public class App {
    private static String[] emails;

    public static void main(String[] args) {
        if (args.length > 0) {
            new EmailParser(args[0]);
        } else {
            new EmailParser("/home/davis/IdeaProjects/phishing-email-detector/emails/phishing/");
        }
    }
}
