/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PhishingEmailDetector;

public class App {
    public static void main(String[] args) {
        EmailParser emailParser;
        if (args.length > 0) {
            emailParser = new EmailParser(args[0]);
        } else {
            emailParser = new EmailParser("/home/davis/IdeaProjects/phishing-email-detector/emails/phishing/");
            //emailParser = new EmailParser("/home/davis/IdeaProjects/phishing-email-detector/emails/benign/");
            //emailParser = new EmailParser("/home/davis/IdeaProjects/phishing-email-detector/emails/mine_phishing/");
        }
        emailParser.testEmails();
    }
}
